backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "news"
    label: "Berita"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - { label: "Gambar Utama (path)", name: "image", widget: "image" }
      - { label: "Ringkasan", name: "summary", widget: "text" }
      - { label: "Konten", name: "body", widget: "markdown" }

  - name: "agenda"
    label: "Agenda"
    folder: "content/agenda"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - { label: "Lokasi", name: "location", widget: "string" }
      - { label: "Deskripsi", name: "body", widget: "markdown" }

  - name: "gallery"
    label: "Galeri"
    folder: "content/gallery"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Judul / Keterangan", name: "title", widget: "string" }
      - { label: "Gambar", name: "image", widget: "image" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
